export enum LEAD_STATUS {
  PARSED = 'PARSED',
  FAILED = 'FAILED',
}

export enum LEAD_COLUMN_TYPE {
  IGNORE = 'IGNORE',
  FIRST_NAME = 'FIRST_NAME',
  LAST_NAME = 'LAST_NAME',
  FULL_NAME = 'FIRST_LAST_NAME',
  PHONE = 'PHONE',
  SECONDARY_PHONE = 'SECONDARY_PHONE',
  ADDRESS_1 = 'ADDRESS_1',
  ADDRESS_2 = 'ADDRESS_2',
  FULL_ADDRESS = 'ADDRESS_1+2',
  CITY = 'CITY',
  ZIP_CODE = 'ZIP_CODE',
  STATE = 'STATE',
  COUNTRY = 'COUNTRY',
  ORIGINAL_IDENTIFIER = 'ORIGINAL_IDENTIFIER',
  SUPPORT_SITE = 'SUPPORT_SITE',
  PURCHASE_SITE = 'PURCHASE_SITE',
  PURCHASE_DATE = 'PURCHASE_DATE',
  PURCHASE_AMOUNT = 'PURCHASE_AMOUNT',
  PRODUCT_NAME = 'PRODUCT_NAME',
  CREDIT_CARD_NAME = 'CREDIT_CARD_NAME',
}

export enum LEAD_DENY_STATUS {
  ALLOWED = 'ALLOWED',
  DENIED = 'DENIED',
  PENDING_DENY = 'PENDING_DENY',
}
export enum AVAILABILITY_STATUS {
  CALL_HOURS_MISMATCHED = 'CALL_HOURS_MISMATCHED',
  AVAILABLE = 'AVAILABLE',
  CALL_IN_FUTURE = 'CALL_IN_FUTURE',
}
export enum HLR_STATUS {
  VALID = 'VALID',
  NOT_VALID = 'NOT_VALID',
  DISABLED = 'DISABLED',
  QUEUED = 'QUEUED',
}
export enum LEAD_STATE {
  DENYLIST = 'DENYLIST',
  PHONE_NORMALIZED_NOT_SPECIFIED = 'PHONE_NORMALIZED_NOT_SPECIFIED',
  HLR_NOT_VALID = 'HLR_NOT_VALID',
  DUPLICATE_LEAD_ID = 'DUPLICATE_LEAD_ID',
  PAUSED = 'PAUSED',
  EMPTY = 'EMPTY',
  SHOW_CALLS = 'SHOW_CALLS',
}
export enum TRI_STATUS {
  ANY = 'ANY',
  YES = 'YES',
  NO = 'NO',
}
