//------------- user group ----------------
export enum USER_GROUP_TYPE {
  DESK = 1,
  SKILL_GROUP = 2,
  GROUP = 3,
}

//------------- filter group -----------------
export enum FILTER_CONTROL {
  OFF = 'OFF',
  WEIGHT = 'WEIGHT',
  FAILOVER = 'FAILOVER',
}

export enum FILTER_GROUP_SETTING {
  CAMPAIGN = 'CAMPAIGN',
  LEAD_FILE = 'LEAD_FILE',
  LEAD_WEIGHT = 'LEAD_WEIGHT',
  PREDEFINED_OBJECT_LIST = 'PREDEFINED_OBJECT_LIST',
  CAMPAIGN_TIME_ZONE = 'CAMPAIGN_TIME_ZONE',
  FEEDBACK_STATUS = 'FEEDBACK_STATUS',
  SYSTEM_STATUS = 'SYSTEM_STATUS',
  STATUS_HAS_CHANGED = 'STATUS_HAS_CHANGED',
  LEAD_ASSIGN_TO = 'LEAD_ASSIGN_TO',
  PURCHASE_DATE = 'PURCHASE_DATE',
}

export enum FILTER_GROUP_CONNECTOR {
  AND = 'AND',
  OR = 'OR',
}

export enum FILTER_GROUP_STATE_OPTIONS {
  IS = 'IS',
  IS_NOT = 'IS_NOT',
  INTO = 'INTO',
  IS_MORE_THAN = 'IS_MORE_THAN',
  MORE_THAN_LAST_HOURS = 'MORE_THAN_LAST_HOURS',
  MORE_THAN_LAST_DAYS = 'MORE_THAN_LAST_DAYS',
  IS_LESS_THAN = 'IS_LESS_THAN',
  LESS_THAN_LAST_HOURS = 'LESS_THAN_LAST_HOURS',
  LESS_THAN_LAST_DAYS = 'LESS_THAN_LAST_DAYS',
  EQUAL = 'EQUAL',
  NOT_EQUAL = 'NOT_EQUAL',
  EQUAL_LAST_HOURS = 'EQUAL_LAST_HOURS',
  EQUAL_LAST_DAYS = 'EQUAL_LAST_DAYS',
  CONTAINS = 'CONTAINS',
  NOT_CONTAINS = 'NOT_CONTAINS',
  WITHIN_LAST_DAYS = 'WITHIN_LAST_DAYS',
  WITHIN_LAST_HOUR = 'WITHIN_LAST_HOUR',
  WITHIN_LAST_MINUTE = 'WITHIN_LAST_MINUTE',
  NOT_WITHIN_LAST_DAYS = 'NOT_WITHIN_LAST_DAYS',
  NOT_WITHIN_LAST_HOUR = 'NOT_WITHIN_LAST_HOUR',
  NOT_WITHIN_LAST_MINUTE = 'NOT_WITHIN_LAST_MINUTE',
}

//------------- predictive settings -----------------
export enum PREDICTIVE_TYPE {
  FIXED = 'FIXED',
  DYNAMIC = 'DYNAMIC',
}

export enum SORTING_METHOD {
  HIGHEST_WEIGHT = 'HIGHEST_WEIGHT',
  FAILOVER = 'FAILOVER',
}
